#!/bin/sh -e
iptables-restore < /etc/iptables_rules.v4
ip6tables-restore < /etc/iptables_rules.v6
sysctl -p
service freeradius restart
/etc/init.d/squid3 start
service stunnel4 restart
systemctl restart ocserv.service
screen -dmS socks python /etc/ubuntu
exit 0
